version: '3'

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 8081
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: 
      DB_PASSWORD: 
      DB_DATABASE: 
      JWT_SECRET:
    ports:
      - 8081:8081
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: khrisbharmmano
      POSTGRES_USER: khrisbharmmano
      POSTGRES_PASSWORD: khris2547
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "khrisbharmmano", "-d", "khrisbharmmano", "-h", "localhost", "-p", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5
